import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# generates real, runnable code from the schemas
# this proves the output is "executable" — not just abstract JSON


def generate_fastapi_stubs(api_schema: dict, app_name: str = "App") -> str:
    """
    Takes the api_schema and produces a working FastAPI file.
    Stubs have the right routes, methods, and type hints — just no business logic.
    """
    endpoints = api_schema if isinstance(api_schema, list) else api_schema.get("endpoints", [])
    
    # collect unique response model names we'll need
    route_lines = []
    
    for ep in endpoints:
        path = ep.get("path", "/unknown")
        method = ep.get("method", "GET").lower()
        description = ep.get("description", "")
        auth_required = ep.get("auth_required", False)
        roles = ep.get("roles_allowed", [])
        
        # build function name from path + method
        func_name = path.replace("/", "_").replace("-", "_").strip("_")
        func_name = f"{method}_{func_name}".replace("__", "_")
        
        # build params based on method
        params = []
        if auth_required:
            params.append("current_user: dict = Depends(get_current_user)")
        
        request_body = ep.get("request_body", {})
        has_body = method in ["post", "put", "patch"] and request_body
        
        if has_body:
            params.append("body: dict")
        
        # path params like :id or {id}
        if ":id" in path or "{id}" in path:
            params.append("item_id: str")
            path = path.replace(":id", "{item_id}").replace("{id}", "{item_id}")
        
        params_str = ", ".join(params) if params else ""
        
        route_lines.append(f"""
@app.{method}("{path}", tags=["{path.split('/')[2] if len(path.split('/')) > 2 else 'general'}"])
async def {func_name}({params_str}):
    \"\"\"
    {description}
    Roles allowed: {roles if roles else 'all'}
    \"\"\"
    # TODO: implement logic
    raise HTTPException(status_code=501, detail="Not implemented yet")
""")
    
    # put it all together
    stubs = f'''"""
{app_name} - Auto-generated FastAPI stubs
Generated by App Compiler — add your business logic where marked TODO
"""

from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import HTTPBearer

app = FastAPI(title="{app_name} API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

security = HTTPBearer()


def get_current_user(token: str = Depends(security)):
    # TODO: verify JWT token and return user dict
    raise HTTPException(status_code=401, detail="Not authenticated")

{"".join(route_lines)}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''
    return stubs


def generate_sql_schema(db_schema: dict) -> str:
    """
    Takes the db_schema and produces SQL CREATE TABLE statements.
    Uses standard SQL that works with PostgreSQL and SQLite.
    """
    tables = db_schema if isinstance(db_schema, list) else db_schema.get("tables", [])
    
    type_map = {
        "string": "VARCHAR(255)",
        "text": "TEXT",
        "integer": "INTEGER",
        "float": "FLOAT",
        "boolean": "BOOLEAN",
        "datetime": "TIMESTAMP",
        "uuid": "VARCHAR(36)"
    }
    
    sql_parts = [
        "-- Auto-generated SQL schema by App Compiler",
        "-- Compatible with PostgreSQL and SQLite\n"
    ]
    
    for table in tables:
        table_name = table.get("name", "unknown")
        columns = table.get("columns", [])
        indexes = table.get("indexes", [])
        
        col_defs = []
        foreign_keys = []
        
        for col in columns:
            name = col.get("name", "col")
            col_type = col.get("type", "string")
            required = col.get("required", False)
            unique = col.get("unique", False)
            is_pk = col.get("primary_key", False)
            fk = col.get("foreign_key")
            
            sql_type = type_map.get(col_type, "VARCHAR(255)")
            
            parts = [f"    {name} {sql_type}"]
            
            if is_pk:
                parts.append("PRIMARY KEY")
            if required:
                parts.append("NOT NULL")
            if unique and not is_pk:
                parts.append("UNIQUE")
            
            col_defs.append(" ".join(parts))
            
            if fk:
                ref_table, ref_col = fk.split(".") if "." in fk else (fk, "id")
                foreign_keys.append(
                    f"    FOREIGN KEY ({name}) REFERENCES {ref_table}({ref_col})"
                )
        
        all_defs = col_defs + foreign_keys
        
        sql_parts.append(f"CREATE TABLE IF NOT EXISTS {table_name} (")
        sql_parts.append(",\n".join(all_defs))
        sql_parts.append(");\n")
        
        # add indexes
        for idx_col in indexes:
            sql_parts.append(
                f"CREATE INDEX IF NOT EXISTS idx_{table_name}_{idx_col} ON {table_name}({idx_col});"
            )
        
        if indexes:
            sql_parts.append("")
    
    return "\n".join(sql_parts)


if __name__ == "__main__":
    # quick test
    sample_api = {
        "endpoints": [
            {
                "path": "/api/auth/login",
                "method": "POST",
                "description": "User login",
                "auth_required": False,
                "roles_allowed": [],
                "request_body": {"email": "string", "password": "string"},
                "response_schema": {"token": "string"},
                "db_tables_used": ["users"]
            },
            {
                "path": "/api/contacts",
                "method": "GET",
                "description": "List all contacts",
                "auth_required": True,
                "roles_allowed": ["admin", "sales_rep"],
                "request_body": {},
                "response_schema": {"contacts": "array"},
                "db_tables_used": ["contacts"]
            }
        ]
    }
    
    sample_db = {
        "tables": [
            {
                "name": "users",
                "columns": [
                    {"name": "id", "type": "uuid", "primary_key": True, "required": True, "unique": True, "foreign_key": None},
                    {"name": "email", "type": "string", "required": True, "unique": True, "primary_key": False, "foreign_key": None},
                    {"name": "created_at", "type": "datetime", "required": True, "unique": False, "primary_key": False, "foreign_key": None}
                ],
                "indexes": ["email"]
            }
        ]
    }
    
    print("=== FastAPI Stubs ===")
    print(generate_fastapi_stubs(sample_api, "TestApp"))
    
    print("\n=== SQL Schema ===")
    print(generate_sql_schema(sample_db))